image: "ubuntu:18.04"
variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get update && apt-get install -y qt5-default build-essential libfuse2 file cmake wget libssl-dev zlib1g-dev

pages:
  only:
    - master
  artifacts:
    paths:
    - public
    expire_in: 1 weeks
  script:
    - ./build.sh
    - mkdir public && mv ./build/Garuda_Downloader-x86_64.* ./public/

testing:
  only:
    - testing
  artifacts:
    paths:
    - public
    expire_in: 1 weeks
  script:
    - ./build.sh
    - mkdir public && mv ./build/Garuda_Downloader-x86_64.* ./public/
